FROM aethereng/codeaster-seq:latest

# salome_meca 2019.0.1 universal + code_aster 15.0.16 sequential.

ADD salome_meca-2020.0.1-1-universal.run /salome_meca.run
ADD bld/build_salome_meca.sh /

ENV PATH=$PATH:/scif/apps/salome_meca/appli_V2020_univ

USER root
RUN /build_salome_meca.sh && rm -f /build_salome_meca.sh

USER aster
